apiVersion: v1
kind: Pod
metadata:
  labels:
    app: backend
    env: prod
  name: be-postgres
spec:
  containers:
  - image: postgres:10.4
    name: be-postgres
    ports:
    - containerPort: 5432

#kubectl apply -f pod-be.yaml
#kubectl get pods -o wide
